on:
  push:
    branches:
      - 'master'
env:
  AWS_SESSION_NAME: gh-action-quickhost
  AWS_REGION: us-east-1
  AWS_QH_ROLE_ARN: arn:aws:iam::${{ secrets.CI_AWS_ACCOUNT }}:role/ghactions-quickhost-ci

jobs:
  build-linux-amd64:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ env.AWS_QH_ROLE_ARN }}
        role-session-name: ${{ env.AWS_SESSION_NAME }}

    - name: Checkout quickhost
      run : |
        pip install -e .

    - name: Fetch plugins
      uses: actions/checkout@v2
      with:
        path: quickhost-plugins
        repository: 'zeebrow/quickhost-plugins'

    - name:  Install plugins
      run: |
        pip install -e quickhost-plugins/plugins/aws/
