name: quickhost

on:
  push:
    branches:
      - master
env:
  AWS_S3_UPLOAD_SESSION: gh-action-quickhost-ci
  AWS_S3_UPLOAD_REGION: us-east-1
  AWS_S3_UPLOAD_ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/ghactions-drcat-s3-upload

jobs:
  build-linux-amd64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.7' # semver syntax
        #architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Install
      run: |
        # just using this to make sure steps run on the same host!
        cat /etc/ssh/ssh_host_ed25519_key.pub
        whoami
        pwd
        ls -lah
        pip install -r requirements.txt
        pip install -e .

    - name: checkout plugins
      uses: actions/checkout@v3
      with:
        repository: zeebrow/quickhost-plugins
    - name: Install plugin
      run: |
        cat /etc/ssh/ssh_host_ed25519_key.pub
        whoami
        pwd
        ls -lah
        pip install -e quickhost-plugins/plugins/aws
    - name: run a command

