on:
  push:
    branches:
      - 'master'
env:
  AWS_SESSION_NAME: gh-action-quickhost
  AWS_REGION: us-east-1
  AWS_QH_ROLE_ARN: arn:aws:iam::${{ secrets.CI_AWS_ACCOUNT }}:role/ghactions-quickhost-ci
  PROG_NAME: main.py

jobs:
  build:
    strategy:
      matrix:
        #python-version: ["3.7", "3.8", "3.9", "3.10"]
        python-version: ["3.9", "3.10", "3.11"]
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
        cache: pip

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ env.AWS_QH_ROLE_ARN }}
        role-session-name: ${{ env.AWS_SESSION_NAME }}

    - name: Checkout quickhost
      run : |
        pip install -e .

    - name: Fetch plugins
      uses: actions/checkout@v2
      with:
        path: quickhost-plugins
        repository: 'zeebrow/quickhost-plugins'

    - name:  Install plugins
      run: |
        pip install -e quickhost-plugins/plugins/aws/

    - name: Run a command
      run: |
        aws sts get-caller-identity
        ${{ env.PROG_NAME }} -h
